NAME = libftprintf.a
CFALGS = -Wall -Wextra -Werror
CC = cc
SRC = conversions/ft_putchar.c ft_printf.c
OBJ = $(SRC:.c=.o)

all : $(NAME)

$(NAME)	: $(OBJ) 
	ar rcs $(NAME) $(OBJ)

%.o: %.c ft_printf.h
	$(CC) $(CFLAGS) -c $< -o $@

clean :
	rm -f $(OBJ)

fclean : clean
	rm -f $(NAME)

re : fclean all

.PHONY : clean fclean re
